// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// bidir_dshot_x1 //
// -------------- //

#define bidir_dshot_x1_wrap_target 0
#define bidir_dshot_x1_wrap 28
#define bidir_dshot_x1_pio_version 0

static const uint16_t bidir_dshot_x1_program_instructions[] = {
            //     .wrap_target
    0x8000, //  0: push   noblock
    0xe081, //  1: set    pindirs, 1
    0xe001, //  2: set    pins, 1
    0x80a0, //  3: pull   block
    0x6070, //  4: out    null, 16
    0xed00, //  5: set    pins, 0                [13]
    0x6d01, //  6: out    pins, 1                [13]
    0xea01, //  7: set    pins, 1                [10]
    0x00e5, //  8: jmp    !osre, 5
    0xe034, //  9: set    x, 20
    0xa0eb, // 10: mov    osr, ~null
    0xe080, // 11: set    pindirs, 0
    0x01cc, // 12: jmp    pin, 12                [1]
    0xe046, // 13: set    y, 6
    0x0010, // 14: jmp    16
    0xe14d, // 15: set    y, 13                  [1]
    0x00d5, // 16: jmp    pin, 21
    0x0090, // 17: jmp    y--, 16
    0x4061, // 18: in     null, 1
    0x004f, // 19: jmp    x--, 15
    0x0000, // 20: jmp    0
    0xe146, // 21: set    y, 6                   [1]
    0x0018, // 22: jmp    24
    0xe14d, // 23: set    y, 13                  [1]
    0x00da, // 24: jmp    pin, 26
    0x000d, // 25: jmp    13
    0x0098, // 26: jmp    y--, 24
    0x40e1, // 27: in     osr, 1
    0x0057, // 28: jmp    x--, 23
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program bidir_dshot_x1_program = {
    .instructions = bidir_dshot_x1_program_instructions,
    .length = 29,
    .origin = -1,
    .pio_version = bidir_dshot_x1_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config bidir_dshot_x1_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + bidir_dshot_x1_wrap_target, offset + bidir_dshot_x1_wrap);
    return c;
}
#endif

